// <auto-generated />
using DataStorageService.Endpoints.DataStorage.AggregateData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataStorageService.Migrations
{
    [DbContext(typeof(AggregateDataContext))]
    partial class AggregateDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DataStorageService.Endpoints.DataStorage.AggregateData.AggregateDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ConversionKey");

                    b.Property<int>("RackCoordinateX");

                    b.Property<int>("RackCoordinateY");

                    b.Property<int>("RackIdentifier");

                    b.Property<int>("RawIntensity");

                    b.Property<string>("RoomNumber")
                        .IsRequired();

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("AggregateDataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
